name: pizza_order_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  go_router: ^11.1.4
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.5
  riverpod_lint: ^2.3.2
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializer: ^0.2.0

flutter:
  uses-material-design: true
